domainName :
  - "yours adminName1"
  - "yours adminName2"
#群聊id
groupID: -123456
#机器人token
botToken : "aaaaaaaaaaa"
alternate:
  test:
    name: "测试"
    newDomainName:
      - "https://111.com"
      - "https://222.top"